name: Rollback Laravel

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release to rollback to"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rollback
        run: |
          set -e

          DEPLOY_PATH="/home/testcicd/domains/cicdtest.salamsch.org"
          RELEASE="${{ inputs.release }}"

          echo "Rollback target: $RELEASE"

          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
              set -e

              cd ${DEPLOY_PATH}

              echo 'Available releases:'
              ls -1dt releases/*

              echo 'Checking target release...'

              test -d releases/${RELEASE}

              echo 'Target release exists.'

              echo 'Current release:'
              readlink current

              ln -sfn releases/${RELEASE} current

              echo 'Rollback completed.'

              echo 'Current release after rollback:'
              readlink current
            "